name: Deploy to UAT Full

# concurrency: 1

on:
  workflow_dispatch:

jobs:
  deploy:
    name: "Deploy Bundle"
    runs-on: ubuntu-latest
    environment: UAT

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install databricks CLI
        uses: databricks/setup-cli@main
    
      
      - name: Validate
        env:
            DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST }}
            DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: databricks bundle validate
      
      - name: Deploy Bundle
        env:
            DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST }}
            DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
            DATABRICKS_BUNDLE_ENV: uat
        run: databricks bundle deploy -t uat

  job_run:
    name: "Run Databricks Workflow"
    runs-on: ubuntu-latest
    environment: UAT

    needs:
      - deploy

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install databricks CLI
        uses: databricks/setup-cli@main

      - name: Run pipeline update
        shell: bash
        run: |
          set -o pipefail
          databricks bundle run --params "mode=full" -t uat databricks_configure_job --refresh-all 2>&1 | tee output.log
        env:
          DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          DATABRICKS_BUNDLE_ENV: dev
